# Generated by Django 3.0.2 on 2020-01-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reciept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Commodity', models.CharField(max_length=100)),
                ('Balance', models.CharField(max_length=100)),
                ('Name_buyer', models.CharField(max_length=100)),
                ('Time_purchased', models.DateTimeField(verbose_name='Last Updated')),
                ('Amount_deposited', models.CharField(max_length=100)),
            ],
        ),
    ]
