# Generated by Django 3.0.2 on 2020-01-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_reciept'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Commodity_Name', models.CharField(max_length=100)),
                ('Price', models.CharField(max_length=100)),
                ('Date_included', models.DateTimeField(verbose_name='Last Updated')),
            ],
        ),
    ]
