# Generated by Django 3.0.2 on 2020-01-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_commodity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciept',
            name='Time_purchased',
            field=models.DateTimeField(blank=True, verbose_name='Last Updated'),
        ),
    ]
