# Generated by Django 3.0.2 on 2020-01-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20200128_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciept',
            name='Time_purchased',
            field=models.DateTimeField(verbose_name='Last Updated'),
        ),
    ]
