# Generated by Django 3.0.2 on 2020-01-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20200128_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciept',
            name='Unique_signature',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reciept',
            name='Updated_balance',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
