# Generated by Django 3.0.2 on 2020-01-31 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_reciept_new_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciept',
            name='Amount_deposited',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reciept',
            name='Updated_balance',
            field=models.IntegerField(max_length=200, null=True),
        ),
    ]
