# Generated by Django 3.0.2 on 2020-01-31 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_auto_20200130_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciept',
            name='Amount_deposited',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reciept',
            name='Updated_balance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
