# Generated by Django 3.0.2 on 2020-01-31 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_auto_20200130_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciept',
            name='idd',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
