# Generated by Django 3.0.2 on 2020-01-31 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_reciept_idd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reciept',
            name='New_signature',
        ),
    ]
