# Generated by Django 3.0.2 on 2020-02-01 18:22

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_remove_reciept_new_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='photo',
            field=models.FileField(default=1, storage=django.core.files.storage.FileSystemStorage(location='media/photos'), upload_to=''),
            preserve_default=False,
        ),
    ]
