# Generated by Django 3.0.2 on 2020-02-01 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0013_comment_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='photo',
            field=models.FileField(upload_to='photos'),
        ),
    ]
