# Generated by Django 3.0.2 on 2020-02-02 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0017_auto_20200201_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciept',
            name='commodity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='register.Commodity'),
            preserve_default=False,
        ),
    ]
