# Generated by Django 3.0.2 on 2020-02-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0018_reciept_commodity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_student', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(verbose_name='Last Updated')),
            ],
        ),
    ]
