# Generated by Django 3.0.2 on 2020-02-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0019_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermOfYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimester_period', models.CharField(max_length=100)),
            ],
        ),
    ]
