# Generated by Django 3.0.2 on 2020-02-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0020_termofyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_subject', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(verbose_name='Last Updated')),
            ],
        ),
        migrations.RemoveField(
            model_name='reciept',
            name='Commodity',
        ),
    ]
