# Generated by Django 3.0.2 on 2020-02-02 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0022_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_test', models.IntegerField(blank=True, null=True)),
                ('second_text', models.IntegerField(blank=True, null=True)),
                ('exam', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('class_of_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Students')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.TermOfYear')),
            ],
        ),
    ]
