# Generated by Django 3.0.2 on 2020-02-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0024_userauth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userauth',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='userauth',
            name='username',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
