# Generated by Django 3.0.2 on 2020-02-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0026_auto_20200202_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
