# Generated by Django 3.0.2 on 2020-02-07 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0028_auto_20200206_0240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_teacher', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(verbose_name='Last Updated')),
            ],
        ),
        migrations.AddField(
            model_name='students',
            name='current_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.Class'),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.Teacher'),
        ),
    ]
