# Generated by Django 3.0.2 on 2020-02-07 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0029_auto_20200207_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.Teacher', to_field='date_added'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='date_added',
            field=models.DateTimeField(unique=True, verbose_name='Last Updated'),
        ),
    ]
