# Generated by Django 3.0.2 on 2020-02-08 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0031_auto_20200207_0603'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembersOfClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Class')),
                ('Students_of_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Students')),
            ],
        ),
    ]
