# Generated by Django 3.0.2 on 2020-02-08 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0034_auto_20200208_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='class_as_of_registration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.Class'),
        ),
        migrations.AlterField(
            model_name='students',
            name='current_class',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
