# Generated by Django 3.0.2 on 2020-03-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0039_auto_20200306_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='photo',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
