# Generated by Django 3.0.4 on 2020-04-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0040_page_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(verbose_name='Laast Updated')),
                ('photo', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/')),
                ('paystack_url', models.CharField(max_length=200, unique=True)),
                ('item_name', models.CharField(max_length=100, unique=True)),
                ('item_description', models.TextField(blank=True, verbose_name='Page Content')),
            ],
        ),
    ]
