# Generated by Django 3.0.4 on 2020-04-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0041_gallery_shoppingitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='name_of_item',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
