# Generated by Django 3.0.4 on 2020-04-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0043_auto_20200412_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingitem',
            name='paystack_url',
            field=models.URLField(unique=True),
        ),
    ]
