# Generated by Django 3.0.4 on 2020-04-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0044_auto_20200413_0358'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=160)),
                ('page_heading', models.CharField(max_length=12, unique=True)),
                ('update_date', models.DateTimeField(verbose_name='Last Updated')),
                ('page_paragraph', models.CharField(max_length=200)),
                ('page_about_us', models.CharField(max_length=200)),
                ('page_display_heading1', models.CharField(max_length=200)),
                ('page_display_heading2', models.CharField(max_length=200)),
                ('page_display_paragraph', models.CharField(max_length=200)),
                ('page_display_image', models.ImageField(upload_to='images/')),
                ('page_footer_paragraph', models.CharField(max_length=200)),
                ('page_footer_location_paragraph', models.CharField(max_length=200)),
                ('page_footer_phonemumber_paragraph', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
