# Generated by Django 3.0.4 on 2020-04-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0045_auto_20200415_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingitem',
            name='priority_level',
            field=models.IntegerField(default=1),
        ),
    ]
