# Generated by Django 3.0.4 on 2020-04-17 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0046_shoppingitem_priority_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingitem',
            options={'ordering': ['priority_level']},
        ),
    ]
